### ISSUE TITLE
Add Terms and conditions

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#100]
Use this copy:

By using the Water Reporter web site, Water Reporter mobile web or Water Reporter iPhone app, Water Reporter Android app, services of Chesapeake Commons ("Water Reporter"), you are agreeing to be bound by the following terms and conditions (“Terms of Service”).
Basic Terms
You must be 13 years and older to use this site.
You are responsible for any activity that occurs under your user account.
You are responsible for keeping your password secure.
You must not abuse, harass, threaten, invade the privacy of, or intimidate other Water Reporter members or staff.
You may not use Water Reporter for any illegal or unauthorized purpose. International members agree to comply with all local laws regarding online conduct and acceptable content.
You are solely responsible for your conduct and any data, text, information, screen names, graphics, photos, profiles, links (“Content”) that you submit, post, and display on Water Reporter.
You must not modify, adapt or hack Water Reporter or modify another website so as to falsely imply that it is associated with Water Reporter.
You must not create or send unwanted notes to any members of the Water Reporter community that would be considered to be spam.
You must not transmit any worms or viruses or any code of a destructive nature.
You must not, in the use of Water Reporter, violate any laws in your jurisdiction (including but not limited to copyright laws).
Violation of any of these agreements will result in the termination of your Water Reporter account. While Water Reporter prohibits such conduct and content on its site, you understand and agree that Water Reporter cannot be responsible for the Content posted on its web site and you nonetheless may be exposed to such materials and that you use Water Reporter at your own risk.

General Conditions
We reserve the right to modify or terminate Water Reporter for any reason, without notice at any time.
We reserve the right to alter these Terms of Service at any time. If the alterations constitute a material change to the Terms of Service, we will notify you via the email address associated with your Water Reporter account in a timely manner.
What constitutes a "material change" will be determined at our sole discretion, in good faith and using common sense and reasonable judgement.
We reserve the right to refuse service to anyone for any reason at any time.
You own all of the content that you share on Water Reporter. You give us permission to use, store, and share the member content you post on Water Reporter. You may request that your account be deleted at any time, though if you've shared your content publicly, the content may persist on third party sites until it is deleted.
You grant Water Reporter a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use, copy, publicly perform or display, distribute, modify, translate, and create derivative works of any content you post on Water Reporter solely for the purpose for which your content was submitted or made available. This license ends when your account or content are deleted.
We may, but have no obligation to, remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, obscene, invades the privacy of others, or otherwise objectionable or violates any party's intellectual property or these Terms of Service.
We reserve the right to remove any content that we feel may include personally identifiable documentation or scans of documents issued by banks or governments (social security numbers, passport numbers, credit card numbers, drivers licenses, etc.).

**Comment by joshuapowell** [comment]
![screencapture-localhost-9000-terms-1440186462573](https://cloud.githubusercontent.com/assets/569351/9417640/f9faa2d2-481b-11e5-9db0-8fed3f5feec4.png)
