### ISSUE TITLE
Landing Page Copy

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#101]
Experience, Capture, Share

Water Reporter is the easiest way to document and map your experiences on the world's waterways.  Use our app for iPhone or Android snap a picture while paddling (surfing, fishing, SUPing, canoeing, rafting, scouting wildlife, stream surveying, living the dream, observing pollution), describe your experience with a few words or hashtags, and share.  We’ll keep track of your adventures, add them to the community map, and allow others to explore the world’s lakes, rivers, and oceans as they happen.

Noticed a trash dump, fish kill, or something that just doesn’t look right in your waterway?  Document it with our app and Water Reporter will connect you and your issue to our network of watershed professionals to help resolve the problem.   With a free account, you can comment and view the actions taken by others to address your water quality threat. Water Reporter allows anyone to be the catalyst that sparks a grassroots stream cleanup or a new restoration project that improves the health of a local waterway.

**Comment by rdawes1** [comment]
It's still long but maybe we can find a way to structure it somehow.  The commons landing page could be a good example to start but in any case we'll get it sorted...app pictures are coming next

*Also, notice that in the second sentence of the first paragraph we have a bunch of activities in parentheses.  I think it would be cool if we could cycle through those similar to the mapbox landing page that is like:  Build the map your app (pin, etc.) deserves

**Comment by rdawes1** [comment]
![img_2295](https://cloud.githubusercontent.com/assets/3653904/9309108/943020d8-44d5-11e5-949d-a1be367b99a6.PNG)
![img_2296](https://cloud.githubusercontent.com/assets/3653904/9309107/94301016-44d5-11e5-9426-9aa35e12e1c7.PNG)
![img_2297](https://cloud.githubusercontent.com/assets/3653904/9309109/9436749c-44d5-11e5-98d5-272dc5a9e5a7.PNG)
![img_2298](https://cloud.githubusercontent.com/assets/3653904/9309110/945afb8c-44d5-11e5-834c-3895e7343104.PNG)
![img_2299](https://cloud.githubusercontent.com/assets/3653904/9309111/945c47b2-44d5-11e5-8748-afadc28855e2.PNG)
![img_2300](https://cloud.githubusercontent.com/assets/3653904/9309112/9464bb86-44d5-11e5-8a3c-6cc21eb6f204.JPG)
![img_2301](https://cloud.githubusercontent.com/assets/3653904/9309113/946e6780-44d5-11e5-819a-e1f72081e3da.PNG)

**Comment by joshuapowell** [comment]
Doesn't match our intention ... needs revised.

![screencapture-localhost-9000-1440186799347](https://cloud.githubusercontent.com/assets/569351/9417753/c3ae2a5e-481c-11e5-809b-a80e070347a4.png)

**Comment by joshuapowell** [comment]
I've just posted a new version of the home page of the website. That said, it does not contain any video or slider. I'd like to talk about these a little more next week.

**Comment by joshuapowell** [comment]
<img width="1552" alt="screen shot 2015-08-22 at 2 30 45 pm" src="https://cloud.githubusercontent.com/assets/569351/9425323/62df3c72-48da-11e5-901c-f966f7c8a604.png">

**Comment by joshuapowell** [comment]
<img width="1552" alt="screen shot 2015-08-22 at 2 31 20 pm" src="https://cloud.githubusercontent.com/assets/569351/9425329/7a414888-48da-11e5-901c-c395db8174ae.png">
