### ISSUE TITLE
About Page Copy

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#102]
About Page

Water Reporter is a community dedicated to documenting human interaction with our world’s rivers lakes and streams.  Organizations and citizens have faster, more complete access to capture and share the real time needs and experiences on a river. Water Reporter was created in 2012 by Chesapeake Commons and Viable Industries as a platform to help the Potomac Riverkeeper simply and gather observations from volunteers in the field.

Prior to the creation of Water Reporter, the Potomac Riverkeeper – like many action-oriented environmental groups – relied upon citizen volunteers to find some method of communicating pollution observations to their leaders. The process was time consuming, wrought with opportunities for misteps and lacked transparency. With Water Reporter, volunteers could share pollution reports directly with the Riverkeeper through their smartphone while avoiding the data entry pitfalls of traditional form based reporting. Water Reporter created a platform for open environmental data to be used to inform smarter restoration decision-making. The duration of time from identifying a water quality issue to finding a solution decreased dramatically – with some problems resolved in as little as one day!

The innovative solutions earned Water Reporter the Technology Impact Award in 2013 and propelled future development of the service. Version 2.0, released in 2014, improved the real-time data feed, streamlined the geo-notification system and broadened reports beyond identifying point source pollution problems. Merging open source technology with volunteer monitoring programs allows critical connections to be made between local governments, volunteers, outdoor groups and environmental organizations. The more users and organizations involved, the better Water Reporter can be at keeping constant eyes on our rivers.

From its humble beginnings, the number of organizations and individuals using Water Reporter continues to grow. The Water Reporter team received additional grant funding to release version 3.0 of Water Reporter in summer 2015. With the native apps for iPhone and Android devices, anyone can capture a moment on their waterway and upload a report that includes a photo, comments and hashtags to the Water Reporter network. Restoration oriented organizations active in the same watershed have privileges that allow them to receive an automatic notification to address the concern brought up by a member of the public. This is most beneficial for reporting pollution, tracking organized volunteer activities, or documenting river characteristics worthy of keeping on the radar. Going forward the Team will be rolling out additional features and functionality for administrators and users that will improve the community’s ability to watch out for our rivers.

Water Reporter differs from other social networks in key ways. The following are a few of the unique features of Water Reporter that empowers citizens and stewards to experience, capture and share their waterways.
Individuals and organizations are connected to each other through their geographies - users don’t have to find other like-minded groups prior to sharing experiences or communicating about pollution.  
Reports are available on a real time map and news feed for all users and directly through e-mail to geographically relevant administrators committed to taking action. If livestock have gotten into a stream or trash is building up at a dam, the administrators can take immediate and collective action to address the problem.  
All submitted reports are added to a map so anyone can follow or comment on a report about a hellbender sighting, plan a trash cleanup or identify a faulty sewage outflow.
Restoration professionals can indicate when they’ve taken action on a pollution report by commenting and sharing photos of the remediated issue.

Water Reporter is the best way to respond to immediate pollution threats, follow long term experiences on the river and participate in protecting our nation’s waterways.

**Comment by joshuapowell** [comment]
![screencapture-localhost-9000-about-1440186767862](https://cloud.githubusercontent.com/assets/569351/9417738/af9e39be-481c-11e5-8490-77581d4b6df5.png)
