### ISSUE TITLE
Pin Color for Action

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#103]
We need something like a blue or green outline on map pins where a restoration action has occured

**Comment by joshuapowell** [comment]
![Uploading Screen Shot 2015-08-14 at 3.10.42 PM.png…]()

**Comment by joshuapowell** [comment]
<img width="1548" alt="screen shot 2015-08-14 at 3 10 42 pm" src="https://cloud.githubusercontent.com/assets/569351/9281952/fb3a2e40-4296-11e5-9c00-b671618d0486.png">
