### ISSUE TITLE
Carry at least basic map navigation (zoom/basemap toggle) across entire site

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#104]
If the expansion functionality is possible to add let's do it.  If not no worries.

**Comment by joshuapowell** [comment]
Each page containing a map now behaves as it should.

![screen shot 2015-08-20 at 5 18 20 pm](https://cloud.githubusercontent.com/assets/569351/9395940/7a7902ae-475f-11e5-9142-43271471dce2.png)

![screen shot 2015-08-20 at 5 18 34 pm](https://cloud.githubusercontent.com/assets/569351/9395944/812cded6-475f-11e5-96cc-88aa2dcdc74e.png)

![screen shot 2015-08-20 at 5 18 45 pm](https://cloud.githubusercontent.com/assets/569351/9395949/873649e8-475f-11e5-84ed-744759120751.png)
