### ISSUE TITLE
Logged out Views and Nav Links

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#110]
I know I'm getting super knit picky here but when a user is logged out, if they click on the Water Reporter logo, they should get directed to the landing or app page.  Also the nav links should be:

Explore, Search Community, Login (Blue button like our View Report button)

**Comment by joshuapowell** [comment]
Let's talk about this on the phone at some point, because I strongly disagree with changing the behavior of an element (i.e., logo link)

**Comment by joshuapowell** [comment]
Log in button I'm cool with.

**Comment by rdawes1** [comment]
I'm cool hashing this out.  With many of the social communities we've looked at and modeled the project after, they basically close down the feed unless you're logged in.  Facebook and Insta are some good examples.  If you are logged out you basically get no access and are directed to the landing page to sign up.  Let's decide how we tackle this.
