### ISSUE TITLE
Close and reopen report functionality is no longer there

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#114]
When I log in as brent and close something out, it no longer shows up as closed.  Also once it has been closed I can no longer reopen.

**Comment by joshuapowell** [comment]
Yikes. I'll check that out. I don't understand why that would've changed.

**Comment by joshuapowell** [comment]
All set.
![screen shot 2015-08-21 at 11 04 54 am](https://cloud.githubusercontent.com/assets/569351/9411541/76d3e91c-47f4-11e5-8b2a-5d0f09b60c0b.png)
