### ISSUE TITLE
Lock down data download for use only by admins

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#116]

**Comment by joshuapowell** [comment]
Fixed but not deployed.

![screen shot 2015-08-21 at 11 14 15 am](https://cloud.githubusercontent.com/assets/569351/9411737/c912cca6-47f5-11e5-8946-abea8025c5d9.png)

**Comment by rdawes1** [comment]
Looking good man tested and fully functional!
