### ISSUE TITLE
Report badge on profile page

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#118]
This may have something to do with this issue:  https://github.com/WaterReporter/www.waterreporter.org/issues/90

But the badges sort of cut into the report photo.  See the attached screenshot
![screen shot 2015-08-21 at 10 43 57 am](https://cloud.githubusercontent.com/assets/3653904/9411090/05e6a7be-47f2-11e5-8de2-421be697e4af.png)

**Comment by rdawes1** [comment]
Alsos can we make the link to the individuals profile (Brent in this case) blue?  Sorry to be  knit picky dick but it's good to be able to directly roll to the dude that fixed it.

**Comment by joshuapowell** [comment]
<img width="1552" alt="screen shot 2015-08-21 at 4 19 27 pm" src="https://cloud.githubusercontent.com/assets/569351/9418231/6719a6a2-4820-11e5-95c7-7bb800c5c6c7.png">
