### ISSUE TITLE
Login Page and Signup Page

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#119]
Again super knit picky here but we have some pretty funky alignment with the login button up against the form field.  Form fields are pretty long as well.  Can we style make it a bit cleaner similar to the following screen shot?
![screen shot 2015-08-21 at 11 02 46 am](https://cloud.githubusercontent.com/assets/3653904/9411507/4d19021a-47f4-11e5-8ffd-0c9cc8c4c80f.png)

**Comment by joshuapowell** [comment]
![screen shot 2015-08-21 at 3 14 45 pm](https://cloud.githubusercontent.com/assets/569351/9417064/5e88de76-4817-11e5-9da4-7fe86143b82b.png)

**Comment by rdawes1** [comment]
This is great!
