### ISSUE TITLE
Broken single report page

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#129]
![screen shot 2015-08-24 at 5 51 41 pm](https://cloud.githubusercontent.com/assets/3653904/9453613/8e043e38-4a89-11e5-8825-2c2fcc42aefa.png)

**Comment by joshuapowell** [comment]
![screencapture-localhost-9000-reports-1712-1440593351562](https://cloud.githubusercontent.com/assets/569351/9493669/56d09e4c-4bcf-11e5-80c9-71fb5e79b9df.png)

**Comment by rdawes1** [comment]
All good there
