### ISSUE TITLE
Overlay on home (explore) page shows 2 pins

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#130]
![screen shot 2015-08-24 at 5 51 31 pm](https://cloud.githubusercontent.com/assets/3653904/9453619/9e43f3d8-4a89-11e5-98db-975d226eb85d.png)

**Comment by joshuapowell** [comment]
Resolved with newest release

![Uploading Screen Shot 2015-08-26 at 8.48.43 AM.png…]()
