### ISSUE TITLE
We need to have confirmations on reset password

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#131]
Say something like:  Thanks for using Water Reporter.  We just sent you an email, please follow the instructions to reset your password.

**Comment by joshuapowell** [comment]
![screen shot 2015-08-31 at 5 43 55 pm](https://cloud.githubusercontent.com/assets/569351/9591206/df69fcb2-5007-11e5-931d-843f760b27c9.png)
