### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#132]
Josh, I know you want to stab me but let's add a button in the main nav (logged out) for sign up right before sign in.  We can debate if need be but for now let's see if that works.

**Comment by joshuapowell** [comment]
I'll meet you half way. I will add both Sign up and Log in as navigation items, but you can have one button in the navigation ... not two. 

Do you want the button to be the Log in or the Sign up?

**Comment by rdawes1** [comment]
HAHAHAH ok login :hankey:

**Comment by joshuapowell** [comment]
It's just too much visually that's all :)
