### ISSUE TITLE
When you click no for delete report the prompts get weird looking

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#142]
See screen shot
<img width="1280" alt="screen shot 2015-08-28 at 2 12 27 pm" src="https://cloud.githubusercontent.com/assets/3653904/9553704/db58d8da-4d8e-11e5-8ffc-923f24a73a1a.png">

**Comment by joshuapowell** [comment]
Not experiencing this right now .... don't think I've changed anything to "fix" it though either.

![screen shot 2015-08-31 at 4 46 04 pm](https://cloud.githubusercontent.com/assets/569351/9589935/cefbc11a-4fff-11e5-8525-424a4ded9aa1.png)

![screen shot 2015-08-31 at 4 46 07 pm](https://cloud.githubusercontent.com/assets/569351/9589938/d0f1d8f6-4fff-11e5-81ba-2f18e3b30792.png)
