### ISSUE TITLE
Optimizing the post speed

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#146]
Images take a while to upload.  This isn't a must have for launch but on down the road will need to be addressed on web and mobile.  Josh, Brendan and I talked about rethinking how and when we resize the image.  On mobile it could happen before sending to the server and on web it could be something that happens asynchronously, IE you fill out your stuff, let it go, and it pops you a notification when its all done.  

While it's an edge case, I uploaded a 6mb file and it took roughly 49 seconds.  Not bad but we can do better.

**Comment by joshuapowell** [comment]
I'm closing this one for now. We've decreased upload time from 12.xxs to under 1s.
