### ISSUE TITLE
Tried end to end with Katie and Got shut down on the edit profile page

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#147]
Screenshot Attached, I can't edit or save any updates to the edit profile page
![screen shot 2015-08-28 at 7 46 56 pm](https://cloud.githubusercontent.com/assets/3653904/9559203/b306fa04-4dbd-11e5-829a-e1b9e077215e.png)

**Comment by rdawes1** [comment]
This sill is not resolved.  When a new account gets created I can only add some attributes and then I get shut down.  When I go back and hit "my profile" I get no edit button unless I do a hard refresh. Then when I do edit the profile and go to save I get a 400.

**Comment by joshuapowell** [comment]
I just created a brand new account through the website using the Sign Up page. I then was redirected to my profile page which I was able to update my first and last name. After that I edited the page again and I was able to add title, then saved and added organization name, then saved again change information.

All seems operational on my end.

Can you outline a numbered list of steps for repeating exactly what you're having issues with?

**Comment by rdawes1** [comment]
Alrighty so new behavior.  When I edit my existing profile I get a 400 and it drops the photo.
![screen shot 2015-09-02 at 1 07 16 pm](https://cloud.githubusercontent.com/assets/3653904/9638238/8ecd3cca-5173-11e5-8f9d-65b1924af229.png)
