### ISSUE TITLE
Signup Page Needs First and Last Name Input Fields

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#148]
We do not have any place to input a first name last name or meta about the user.  When they go and create an account, they get no log in or ability to access their profile.

**Comment by joshuapowell** [comment]
We have decided that we will not place First and Last name fields on the registration page. Instead we are going to redirect the user to their Profile Edit page on successful registration. Then, if they don't fill out their name we're going to repeat a warning notification on-screen, on every page telling them they need to update their profile.

That said, we've put things in place to ensure that they can access the "My Profile" page.

**Comment by joshuapowell** [comment]
See 58c3d41
