### ISSUE TITLE
dev.waterreporter.org doesn't work in safari

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#149]
I get the following errors in my consol when I try to load the page
![screen shot 2015-09-01 at 4 37 06 pm](https://cloud.githubusercontent.com/assets/3653904/9616564/d9169a62-50cc-11e5-98c5-3e651cb23ae2.png)

**Comment by joshuapowell** [comment]
I have confirmed that this a build-only issue .. which gives a bit of relief. However, we'll still need to ensure it's building properly the next time around.

<img width="1548" alt="screen shot 2015-09-02 at 11 54 50 am" src="https://cloud.githubusercontent.com/assets/569351/9636461/7db522f4-5169-11e5-845c-8d071eed5761.png">

**Comment by joshuapowell** [comment]
Turns out this is the case in Internet Explorer as well.

After doing some brief investing it looks like we should try and ensure that our app is misusing any reserved keywords.

See http://stackoverflow.com/questions/17035230/angular-js-breaks-in-safari-but-not-chrome

**Comment by joshuapowell** [comment]
That was it, looks like we fixed our problem in Safari. Need to check Internet Explorer.

<img width="1548" alt="screen shot 2015-09-02 at 12 12 55 pm" src="https://cloud.githubusercontent.com/assets/569351/9636907/f4d9e4f8-516b-11e5-8c1d-2e15d80ac6aa.png">

**Comment by joshuapowell** [comment]
Reopening until we check IE 10+

**Comment by joshuapowell** [comment]
Internet Explorer 10 is broken as of right now. It logs out these three messages:

<img width="498" alt="screen shot 2015-09-02 at 12 14 23 pm" src="https://cloud.githubusercontent.com/assets/569351/9636954/339b6ac2-516c-11e5-9e76-c538eb6a8edd.png">

**Comment by joshuapowell** [comment]
Internet Explorer 11 loads absolutely fine, with the exception of a couple of minor image bugs.
