### ISSUE TITLE
background video

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#150]
Doesn't work in Firefox.  I think this is because I gave you a broken MP4.  Please refer to slack and fire in the updated one and I'll test.

**Comment by joshuapowell** [comment]
Looking good my friend ... looking good.

<img width="1552" alt="screen shot 2015-09-02 at 11 53 41 am" src="https://cloud.githubusercontent.com/assets/569351/9636433/49301fd4-5169-11e5-9595-886ca1ffa951.png">
