### ISSUE TITLE
Data Submission Form Will not submit due to lat long

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#151]
I keep getting this prompt for lat long entry even though I've tried moving my pin around

![screen shot 2015-09-01 at 5 20 46 pm](https://cloud.githubusercontent.com/assets/3653904/9616737/e15083ae-50cd-11e5-814a-3166da1ecf5e.png)

**Comment by joshuapowell** [comment]
We implemented a `novalidate` attribute on the form for this page. With this in place it resolves the latitude and longitude warning.

To ensure that comments and a photo are submitted, we have implemented on screen notifications telling the user exactly what is wrong and what needs fixed.

<img width="415" alt="screen shot 2015-09-02 at 11 59 44 am" src="https://cloud.githubusercontent.com/assets/569351/9636571/1fe49e42-516a-11e5-8747-362ba9cfab32.png">

<img width="443" alt="screen shot 2015-09-02 at 11 59 38 am" src="https://cloud.githubusercontent.com/assets/569351/9636573/21d65aa6-516a-11e5-8ed0-04f33764b978.png">

**Comment by joshuapowell** [comment]
The report from this test turned out as follows after all issues were fixed.

<img width="1552" alt="screen shot 2015-09-02 at 12 01 47 pm" src="https://cloud.githubusercontent.com/assets/569351/9636628/72b8294a-516a-11e5-974c-e5e9287a5fa3.png">
