### ISSUE TITLE
Image Bugs in Internet Explorer 11

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#154]
Note the skewing of the logo:

<img width="242" alt="screen shot 2015-09-02 at 12 15 56 pm" src="https://cloud.githubusercontent.com/assets/569351/9637029/7b6177de-516c-11e5-9fa7-5d0ef9ee2f86.png">

Note the comment display:

<img width="360" alt="screen shot 2015-09-02 at 12 16 06 pm" src="https://cloud.githubusercontent.com/assets/569351/9637031/7d15a4ce-516c-11e5-8a1a-808b9296b6c7.png">

**Comment by rdawes1** [comment]
I'm a lot less concerned about explorer...Glad it works in 11 and we don't need to people who can't be bothered to use a modern day browser let alone update :)
