### ISSUE TITLE
Adding a new account and filling out profile details from the web

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#155]
So if I create an account and only fill in first and last name, I get directed right back to the edit page.  The only way I can get my account name to show at the top is if I push the reload button, then I can edit my account.  Here is what I get after I edit my information upon web signup and navigate away from the page
![screen shot 2015-09-02 at 1 09 13 pm](https://cloud.githubusercontent.com/assets/3653904/9638327/32bd4424-5174-11e5-87fb-b3fafed9e878.png)

**Comment by joshuapowell** [comment]
Yeah. That's because your browser is caching the results from the `user/me` request.
