### ISSUE TITLE
Landing Page Text

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#156]
Sorry to keep changing this but we need to update the landing page content to this:  

Water Reporter is the easiest way to document and map your experiences on the world's waterways. Use our app for iPhone or Android to snap a picture while you’re on your adventure, describe your experience with a few words or hashtags, and share. We’ll keep track of your adventures, add them to the community map, and allow others to explore the world’s lakes, rivers, and oceans as they happen.

Noticed a trash dump, fish kill, or something that just doesn’t look right in your waterway? Document it with our app and Water Reporter will connect you and your issue to our network of watershed professionals to help resolve the problem. With a free account, you can comment and view the actions taken by others to address your water quality threat. Water Reporter allows anyone to be the catalyst that sparks a grassroots stream cleanup or a new restoration project that improves the health of a local waterway.

**Comment by joshuapowell** [comment]
Yeah ... next time I see you ... it's on

![url](https://cloud.githubusercontent.com/assets/569351/9642989/2aeef53a-518d-11e5-9384-61180f4d1d3a.jpg)

**Comment by joshuapowell** [comment]
So .. did you change this or do I need to?
