### ISSUE TITLE
About Page Copy and Quick Styling

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#157]
Please use this updated copy and note a few minor things.
1.  I've added some images to this to help make the about page a bit more fun.  
2.  It would be awesome to incorporate our featured reports (just the card...see image) but I can settle for the static image I provided.
3.  I have added a section on what is coming in terms of functioalit and what has been completed.  Could we put this a rough table with some styling that is somewhat comparable to the conservation tracker table?

About Water Reporter

Water Reporter is the fastest growing community dedicated to documenting human interaction with our world’s rivers lakes and streams. Our platform compiles your snapshots with those of other like-minded outdoor river and environmental enthusiasts plus, you can report pollution issues to an on-demand network of stewards dedicated to protecting and solving local water quality issues.

Get started is easy

Signup for an account through the mobile app or website
Use our app for Android or iOS to take a picture, add comments, and share

We’ll keep track of your adventures, add them to the community map, and allow others to explore the world’s lakes, rivers, and oceans as they happen.

Report and Resolve Water Pollution

Noticed a trash dump, spill, or something that just doesn’t look right in your waterway?  Post it and our inspirational community of stewards will help you get it fixed.  

We’ll automatically connect you and your post with restoration professionals working in your watershed. 
Allow you to easily view and comment on progress toward addressing the water quality problem
Help you keep track and share the issue’s you’ve worked with others to resolve.

With Water Reporter, anyone can be the catalyst that sparks a grassroots stream cleanup or a new restoration project that improves the health of a local waterway.  

Always Evolving, Constantly Improving

We are always working to find new and more efficient ways to map experiences on the water and expedite water quality remediation.  Here is are some of the latest functionality we’ve recently completed and will be releasing in the near future. 
Conservation tracker style table:

Feature     Status

Affiliate with Organization (Web + Mobile)  In Development

Marking reports as remediated (Mobile)  In Development

Push Notifications              In Development

Search and Export (Admin)           Complete

Marking reports as remediated (Web) Complete

Commenting on reports (Web)     Complete

Report Submission (Web)         Complete

Personalized Profile Page           Complete

Acting Locally, Expanding Globally

Water Reporter users benefit from an ever expanding network of stewards that actively field and respond to community pollution reports with the goal to enhance local water quality. If you’d like to join our network and help to address the many threats facing water quality, please get in touch.
![acadia](https://cloud.githubusercontent.com/assets/3653904/9642263/2cb3de16-5189-11e5-97dc-d23318ad1fb8.jpg)
![cows_instream](https://cloud.githubusercontent.com/assets/3653904/9642260/2ca8cabc-5189-11e5-90a9-cbb041933dea.jpg)
![jamie_sturgeon](https://cloud.githubusercontent.com/assets/3653904/9642261/2caab1ec-5189-11e5-8d4a-2d9687ad7f75.jpg)
![pointsource pollution](https://cloud.githubusercontent.com/assets/3653904/9642259/2ca9c778-5189-11e5-8985-4758b76425f3.png)
![report_pollution](https://cloud.githubusercontent.com/assets/3653904/9642262/2cae1d0a-5189-11e5-9178-7dd04df47ba7.png)

**Comment by joshuapowell** [comment]
You told me on the phone that you updated this content (again). And that you put it into Github .. but I'm not seeing it. Please make sure you commit.

**Comment by rdawes1** [comment]
Looking good man!  I added a different discharge photo from the legacy system that we will have to add but other then that we are all set
