### ISSUE TITLE
home page image off center from phone

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#158]
the switching iphone image is hanging off of the phone. The shift is worse on Safari than Chrome, at least on my computer.

**Comment by rdawes1** [comment]
Erin,

This depends on screen resolution and is something we should have a look at.  Thanks for bringing this up.  I noticed this yesterday at a presentation.

**Comment by joshuapowell** [comment]
This is a responsive CSS issue. This needs to be resolved. In addition to this one, we know of several other responsive specific display bugs (e.g., single report, form, list, features)

**Comment by joshsager** [comment]
This issue has been resolved. The iPhone now centers.
