### ISSUE TITLE
Sign up page text - sign up vs. register

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#160]
The text on the sign up page says "...and click Register" but the corresponding button says "Sign up". Would be great if they had the same wording.

**Comment by rdawes1** [comment]
Good catch

**Comment by rdawes1** [comment]
Hey sorry Josh but when you get a chance can you change "Register" to Signup on this page:

https://github.com/WaterReporter/www.waterreporter.org/blob/fdad3c7ccd3684cffe2d2c5acad6567f76d75b22/app/modules/shared/security/securityRegister--view.html
