### ISSUE TITLE
Contact E-mail Information

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#164]
Sign up email confirmation (and most draft communication documents) list waterreporter@chesapeakecommons.org as the support e-mail address. If Support@waterreporter.org is the go to email account for all correspondence from outside parties then need to change the "welcome" email to from waterreporter@chesapeakecommons.org to support@waterreporter.org or create another email that we can use for the "Welcome e-mail" questions and comments and future correspondence.

**Comment by joshuapowell** [comment]
Fixed via the WaterReporter API repository.
