### ISSUE TITLE
Edit Existing Report Needs Geocoder, Zoom in-out, and Basemap Toggle

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#165]
Noticed this functionality wasn't in this section

**Comment by rdawes1** [comment]
![screen shot 2015-09-08 at 8 53 36 am](https://cloud.githubusercontent.com/assets/3653904/9735727/d359b9ae-560a-11e5-9e52-c729921b828d.png)

**Comment by joshuapowell** [comment]
Toggler has been added so that these display by default
