### ISSUE TITLE
Text in Confirmation email from Support@waterreporter.org

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#166]
Hey guys, there are a few formatting changes to be made to the text in the welcome e-mail. The "titles" are currently reading as part of the text and it makes for awkward reading right now. 

These are the titles that should either be bolded or changed to a header and put on a separate line:
Submitting a Report in the Field
Continue the Conversation Online

And change the contact e-mail at the bottom to support@waterreporter.org or whatever contact email you choose to use that is functional.

**Comment by joshuapowell** [comment]
![screen shot 2015-09-09 at 4 28 37 pm](https://cloud.githubusercontent.com/assets/569351/9773373/d7010066-570f-11e5-90af-86ad39066337.png)
