### ISSUE TITLE
Profile Map is not loading where the user's last report was taken

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#167]
See screenshot below
![screen shot 2015-09-08 at 9 18 16 am](https://cloud.githubusercontent.com/assets/3653904/9735712/b84ce4b0-560a-11e5-8621-a036bf469594.png)

**Comment by joshuapowell** [comment]
This was because the map was'nt being cleared off properly and the first report was not being picked properly.
