### ISSUE TITLE
Routing with Hashtags

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#170]
Brings in everything with a hashtag and desription not just hashtags

**Comment by joshuapowell** [comment]
I believe that this is resolved, although we need to do further testing.

It came down to a function accidentally running twice ... the reason it was working "sometimes" and not others was dependent on which of the duplicate requests return first. While a dup shouldn't matter, it was messing up the tag on the search during the second pass.
