### ISSUE TITLE
Featured Report Map Doesn't Recenter

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#174]
When moving from one featured report to the next it moves the map to the second featured report you click on but when you go to the third, fourth, fifth, and sixth, it is stuck on the second.  This appears to be a similar bug to the map recenter issue with the form

**Comment by joshuapowell** [comment]
Yeah, I confirmed that this is a problem and was able to repeat this on http://dev.waterreporter.org/

We'll investigate further and circle back.

**Comment by rdawes1** [comment]
Nice thanks man!

**Comment by joshuapowell** [comment]
I believe that this has been fixed. We have pushed the working version to dev.waterreporter.org for testing. Please review this and let us know if it works.

**Comment by joshuapowell** [comment]
@rdawes1 Back in your court for testing on the development server.

**Comment by rdawes1** [comment]
Tested on chrome, firefox, and safari.  All good, I'm closing this one out.
