### ISSUE TITLE
Update DNS Information to point at new IP Address

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#179]

**Comment by joshuapowell** [comment]
Will give B the go ahead when appropriate.

**Comment by joshuapowell** [comment]
John to get credentials from Brendan for DNS information. Josh and John to change these 24 hours prior to launch.

**Comment by joshuapowell** [comment]
When the time is right ... this is the IP 107.170.129.166

**Comment by brendandm** [comment]
Copy that, ready to make the change when I get the nod.
