### ISSUE TITLE
About Page Bug

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#181]
Noticed the about page has the home page great falls image on it now.  
![screen shot 2015-09-21 at 1 53 50 pm](https://cloud.githubusercontent.com/assets/3653904/10000114/369e6f34-6068-11e5-8db2-9bde9069f069.png)

**Comment by joshsager** [comment]
Fixes #181 Adds in logic in page--controller to only display video on the home page
