### ISSUE TITLE
Alert for You Forgot To Upload an Image Sticks

### ISSUE THREAD

**Issue by joshsager** [WaterReporter/www.waterreporter.org#185]
When submitting a report if you forget to upload an image, then upload the image, then submit the report. The you need to upload an image message sticks.

**Comment by joshuapowell** [comment]
If this needs to be implemented anywhere throughout any system all we need to do is call the following and it will clear all onscreen messages.

```
$timeout(function() {
  $rootScope.notifications.objects = null;
}, 3500);
```

The `$timeout` will need to be loaded as a module requirement (i.e., in the function).
