### ISSUE TITLE
Sign-up Page "forgot your password" link

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#197]
This one of a few update suggestions for the sign-up page - a page that is causing a lot of confusion with current and potential users. First, on the sign up page there is a link next to the password field that says "forgot your password". This is confusing for someone setting up a new account because it is really a link that would only be relevant to a current user. I suggest removing it or replacing it with a  link to "password requirements".

**Comment by brendandm** [comment]
![screenshot 2015-10-21 15 13 25](https://cloud.githubusercontent.com/assets/5325391/10647460/7b4c6cfc-7806-11e5-8410-1b33913fed8e.png)

**Comment by joshuapowell** [comment]
Brendan pushed a fix for this task. Unfortunately the tag didn't pick up the keyword.
