### ISSUE TITLE
Sign up page "confirm your password" field

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#198]
This one of a few update suggestions for the sign-up page - a page that is causing a lot of confusion with current and potential users. Right now a new user only enters their password once. To help confirm that this is a sign up page and to reduce any typos in passwords, I'm suggesting adding a "confirm your password" field that validates against the original password field.

**Comment by joshuapowell** [comment]
![screen shot 2016-03-09 at 10 20 41](https://cloud.githubusercontent.com/assets/569351/13639842/97c08b1e-e5e0-11e5-894b-09e21a5e592f.png)
