### ISSUE TITLE
Open Graph isn't working correctly. This might need to be hand coded.

### ISSUE THREAD

**Issue by joshsager** [WaterReporter/www.waterreporter.org#204]
![facebook](https://cloud.githubusercontent.com/assets/1139760/10950088/1ff12f42-8304-11e5-907a-a3be251f4c2e.png)

**Comment by rdawes1** [comment]
Sager,

This is something that I also noticed on report pages as well.  Would be really awesome to have this fixed as it would really bring our share capabilities full circle.

**Comment by joshsager** [comment]
All fixed. 
<img width="527" alt="all betters" src="https://cloud.githubusercontent.com/assets/1139760/11124010/b94ae7f0-8930-11e5-8cdd-b190c32c5946.png">
