### ISSUE TITLE
Resources/Help Page

### ISSUE THREAD

**Issue by hofmerin** [WaterReporter/www.waterreporter.org#205]
Attached file has updated text for the resources pages. Mostly fixes grammatical errors and punctuation typos. Also, in the index, "Hashtags" is listed twice.

[Help_Docs_Edits.docx](https://github.com/WaterReporter/www.waterreporter.org/files/34793/Help_Docs_Edits.docx)

**Comment by rdawes1** [comment]
Awesome!  I'll Get on these when I hop back in the office tom.

**Comment by rdawes1** [comment]
Erin,

I reviewed and made changes accordingly.  I'm going to talk to Brendan about the signup on the home page.
