### ISSUE TITLE
Protected > Single Report: Implement Edit Report Functionality

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#31]
I'm not exactly sure what they should be allowed to `Edit` of the report. It seems like editing user-submitted or crowd-sourced data is unethical in someway.

I feel that the Keeper should either be able to Close, Delete, or Comment, but not Edit the Report in question.

Feedback please?

**Comment by rdawes1** [comment]
Agreed...I think we can counter the issue by getting folks to comment and create a dialogue around the particular report.  That way everything is documented in the open.

**Comment by joshuapowell** [comment]
Perfect. Thanks.
