### ISSUE TITLE
Setup SSL Certificate on the API server

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#35]
Our new SSL certificate has been purchased as an add-on to our existing service package. We are waiting for confirmation of it's completion. At that time we will install the certificate on the WaterReporter API and Dev servers.

**Comment by joshuapowell** [comment]
@rdawes1 @brendandm Whatever happened with the setup of the email? We need to have email setup on your end in order to be able to confirm that we own the domain and then we can setup this SSL certificate. This is not an immediate necessity, but we should set a deadline for this. This absolutely needs done prior to launch.

**Comment by rdawes1** [comment]
May need your help on this again.  You had said to click the "verify" domain button and that after everything propagates we'd be good.  I've tried clicking verify and it fails.  Let me know when you have some time and we'll huddle up and get this sorted out.

**Comment by joshuapowell** [comment]
John and I had a phone conversation about the domain TXT file that Google requires you insert into your domains DNS records. We remove several old TXT records that could've been causing the problem. We re-added the TXT records using the `@` as the "Host Record" in Bluehost.

UPDATE: After approximately 5 hours of waiting it seems that while the deleted records are now gone, that our new record still hasn't propagated. We'll need to keep an eye on this to ensure that something isn't amiss.

**Comment by brendandm** [comment]
Everything is squared away here. Amazon MX and TXT records are in place. Messages can be routed to @waterreporter.org aliases listed in the Chesapeake Commons Google account.

Clear for certificate installation.

**Comment by joshuapowell** [comment]
Email has been sent back to `admin@waterreporter.org`. Please forward to me once we received so that we can complete the SSL setup on the server.

**Comment by joshuapowell** [comment]
I installed the certificate, but it seems that something went wrong, so now we are rekeying the certificate. Waiting.

**Comment by joshuapowell** [comment]
SSL Certificate has been successfully setup on the www.waterreporter.org domain
