### ISSUE TITLE
How to handle anonymous submission under the new user paradigm?

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#42]

**Comment by rdawes1** [comment]
Blarg

**Comment by joshuapowell** [comment]
A new comment

**Comment by joshuapowell** [comment]
Grrr

**Comment by joshuapowell** [comment]
asdfasfasdf

**Comment by rdawes1** [comment]
All good on this.  Anyone using WaterReporter for comment, report submission, etc. needs to have a user account.  We want to boost the number of registered users and don't benefit from anonymous ones
