### ISSUE TITLE
Citizen Level Permissions Bug is Back

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#49]
When I log in as me (dawes@chesapeakecommons.org) I am pretty sure my designation is supposed to be a citizen.  This means I can add, edit, and delete only my comments and bounce around the system.  When I click on my profile (my name from the activity feed) I see 162 (all reports) assigned to me as both open and closed.

**Comment by joshuapowell** [comment]
... we never resolved this. It's only ever been fixed for "logged out" and "admins". The Keeper demo is Admin focused, not "citizen" focused.

**Comment by joshuapowell** [comment]
After looking at it again ... are you sure? Is this the page you see if you're logged in and go to http://dev.waterreporter.org/profiles/4

![screen shot 2015-06-23 at 4 01 56 pm](https://cloud.githubusercontent.com/assets/569351/8315825/39e83dde-19c1-11e5-83a0-dfc0d7fb14c2.png)
