### ISSUE TITLE
Ability to upload images on report closure

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#63]
Riverkeepers who resolve a report need to be able to add a photo when something gets resolved.

**Comment by joshuapowell** [comment]
All user's have the ability to upload images on comments now, not just on closure.

![screen shot 2015-08-13 at 1 10 52 pm](https://cloud.githubusercontent.com/assets/569351/9256301/c72ac1d0-41bc-11e5-80ff-5cf381c60c14.png)

![screen shot 2015-08-13 at 1 10 57 pm](https://cloud.githubusercontent.com/assets/569351/9256302/c9613380-41bc-11e5-831d-cf7bf58581d6.png)
