### ISSUE TITLE
Create Account Email Confirmation

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#86]
Please add the following copy to the email confirmation when a user creates an account:

Hello, Congratulations on joining Water Reporter! You are now officially part of the social network dedicated to mapping your moments on the world’s river and oceans and keeping our waterways clean and clear for future enjoyment. We don’t have a secret handshake, but we do want to give you a few insider tips on how to make the most of Water Reporter. 

Submitting a Report in the Field
To make an impact on water quality, Water Reporter relies on its network of users to go out into their watersheds and then share their experiences through our app. To submit a report:
Use the app on your iPhone or Android to take a photo. 
Add a comment that describes what you’re sharing. Keep it brief, but informative.
Include hashtags! This helps other members who exploring the community.
Feel free to double check the location of your report before sharing.
Share it!
Water Reporter adds your report to the community and e-mails it directly to water quality professionals operating in the same watershed.
As confirmation, you will get an email telling you who received a direct notification of the report.

Continue the Conversation Online
Every report you share gets added to your profile and the community. You can use waterreporter.org to manage all of your reports, explore the network, and reach out to other likeminded people in your watershed.

Sign in at WaterReporter.org to see what others have to say about your reports.  If you shared a report that has to do with water pollution, you can also use WaterReporter.org to track the status of your report and see if other restoration professionals have taken action.
Search through a feed of reports to find other experiences on your rivers, see what other people are saying and discuss wider efforts. 
Check out the focus of restoration professionals in your watershed via their profile pages. You can see reports that have been resolved and provide any follow up insight that you might have. 
You even have your own user profile that compiles all of your reports so that you can share your experiences on the water or view restoration actions that you’ve helped catalyze.

Use the app and check out the website to learn more about how you can be an integral player in mapping and restoring our world’s waterways. And don’t forget to spread the word - the more users and organizations on Water Reporter, the better able we’ll all be to keep our rivers flowing free for now and future generations.

If you have any questions, e-mail us at waterreporter@chesapeakecommons.org. 

Thanks for participating!
The Water Reporter Team

**Comment by joshuapowell** [comment]
![screen shot 2015-08-13 at 1 13 17 pm](https://cloud.githubusercontent.com/assets/569351/9256372/1f25aabc-41bd-11e5-829a-dd1a30477682.png)

**Comment by joshuapowell** [comment]
![screen shot 2015-08-13 at 1 50 39 pm](https://cloud.githubusercontent.com/assets/569351/9257200/5109c496-41c2-11e5-8ba4-ddfa32c5154c.png)

**Comment by joshuapowell** [comment]
Have a look at the email I sent you (live example) or the above screenshot with the appropriate copy. Please let me know if you have any revisions.

**Comment by joshuapowell** [comment]
![screen shot 2015-08-13 at 2 27 56 pm](https://cloud.githubusercontent.com/assets/569351/9258115/82295b4a-41c7-11e5-99da-4076f95eefbe.png)
