### ISSUE TITLE
Copy for Signup Complete Page

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#87]
SIGN UP COMPLETE PAGE

Water Reporter
Thanks for joining Water Reporter, the only social network that connects citizens and stewards for the welfare of their waterways.

You’re now part of an amazing community of more than COUNTER users sharing their experiences in the enjoyment and conservation of rivers and oceans.

Click here to share Water Reporter with your friends or a local environmental organization to keep the Water Reporter community expanding.

Follow us on Twitter, Facebook

**Comment by joshuapowell** [comment]
It seems that this will be getting integrated into the app ... not on the website at all.

**Comment by joshuapowell** [comment]
I dropped the last two lines. We don’t want them navigating away to share or email friends at this point do we?

![screen shot 2015-08-31 at 4 00 07 pm](https://cloud.githubusercontent.com/assets/569351/9588962/5d4ff0d2-4ff9-11e5-9b40-a9fb570bb379.png)
