### ISSUE TITLE
Gravatar Bug

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#91]
We have a weird Gravatar bug that caches the image of "your" user and sometimes puts it in the place of other users. This can't happen. We need to completely remove Gravatar support from this application.

See example below:

Broken:
![screen shot 2015-08-13 at 2 02 26 pm](https://cloud.githubusercontent.com/assets/569351/9257533/0eb08a1a-41c4-11e5-93b7-3c0ff790e7d8.png)

After reload:
![screen shot 2015-08-13 at 2 02 31 pm](https://cloud.githubusercontent.com/assets/569351/9257537/14662320-41c4-11e5-8d69-6f98e04c2ca1.png)

**Comment by rdawes1** [comment]
Pretty sure this has been fixed by implementing our new edit profile page
