### ISSUE TITLE
Hashtags don't search on some pages

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/www.waterreporter.org#93]
If you note the below screenshot you'll notice that the blue links are hashtags ... when you click these they should provide a "Search" using the hashtag and take the user to the search results page.

![screen shot 2015-08-13 at 2 05 16 pm](https://cloud.githubusercontent.com/assets/569351/9257586/5c3e94ac-41c4-11e5-98c0-48fb8ee280e8.png)

**Comment by joshuapowell** [comment]
Update .. hashtags no longer search anywhere ... need to fix this soon

**Comment by joshuapowell** [comment]
URLs like this `http://localhost:9000/search?tag=cows` now execute an actual search

**Comment by rdawes1** [comment]
Kicked the tires and It's good to go!  This functionality is going to be so cool when we get people adopting it!
